/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "avg.h"

int *
addition_1_svc(struct add *argp, struct svc_req *rqstp)
{
	static int  result;
    result = argp->a + argp->b;
	/*
	 * insert server code here
	 */

	return &result;
}
