/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ECHO_H_RPCGEN
#define _ECHO_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>


struct input {
	char buffer[256];
};
typedef struct input input;
#ifdef __cplusplus
extern "C" bool_t xdr_input(XDR *, input*);
#elif __STDC__
extern  bool_t xdr_input(XDR *, input*);
#else /* Old Style C */
bool_t xdr_input();
#endif /* Old Style C */


typedef input data;
#ifdef __cplusplus
extern "C" bool_t xdr_data(XDR *, data*);
#elif __STDC__
extern  bool_t xdr_data(XDR *, data*);
#else /* Old Style C */
bool_t xdr_data();
#endif /* Old Style C */


#define ECHO ((rpc_uint)44)
#define ECHOVER ((rpc_uint)1)

#ifdef __cplusplus
#define getechoserver ((rpc_uint)1)
extern "C" data * getechoserver_1(data *, CLIENT *);
extern "C" data * getechoserver_1_svc(data *, struct svc_req *);

#elif __STDC__
#define getechoserver ((rpc_uint)1)
extern  data * getechoserver_1(data *, CLIENT *);
extern  data * getechoserver_1_svc(data *, struct svc_req *);

#else /* Old Style C */
#define getechoserver ((rpc_uint)1)
extern  data * getechoserver_1();
extern  data * getechoserver_1_svc();
#endif /* Old Style C */

#endif /* !_ECHO_H_RPCGEN */
