/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "echo.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

data *
getechoserver_1(argp, clnt)
	data *argp;
	CLIENT *clnt;
{
	static data clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, getechoserver, xdr_data, argp, xdr_data, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

int main()
{
	
}
