/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "echo.h"

bool_t
xdr_input(xdrs, objp)
	XDR *xdrs;
	input *objp;
{

	if (!xdr_vector(xdrs, (char *)objp->buffer, 256, sizeof(char), (xdrproc_t)xdr_char))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_data(xdrs, objp)
	XDR *xdrs;
	data *objp;
{

	if (!xdr_input(xdrs, objp))
		return (FALSE);
	return (TRUE);
}
