/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "add.h"


void
addprog_1(char *host)
{
	CLIENT *clnt;
	double  *result_1;
	input_data  add_1_arg;
    int i;
    printf("Enter no of terms to add: ");
    scanf("%d",&add_1_arg.n);
    for(i=0;i<add_1_arg.n;i++)
    {
        scanf("%lf",&add_1_arg.a[i]);
    }
#ifndef	DEBUG
	clnt = clnt_create (host, ADDPROG, ADDVERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = add_1(&add_1_arg, clnt);
	if (result_1 == (double *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf("%lf",*result_1);
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	addprog_1 (host);
exit (0);
}
