/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "add.h"

double *
add_1_svc(input_data *argp, struct svc_req *rqstp)
{
	static double  result;
	int i;
	 for(i=0;i<argp->n;i++)
	 {
	    result+=argp->a[i];
	 }

	/*
	 * insert server code here
	 */

	return &result;
}
